import axiosInstance from './axiosInstance';

// Downloads the signed-in voter's own receipt PDF for an election. The PDF
// is generated by the server from the vote record, which never contains
// the chosen candidate.
export async function downloadReceiptPdf(electionId, electionTitle = 'election') {
  const res = await axiosInstance.get(`/api/elections/${electionId}/my-receipt.pdf`, { responseType: 'blob' });
  const url = URL.createObjectURL(res.data);
  const a = document.createElement('a');
  a.href = url;
  a.download = `vote-receipt-${String(electionTitle).replace(/[^\w-]+/g, '_').slice(0, 60)}.pdf`;
  document.body.appendChild(a);
  a.click();
  a.remove();
  setTimeout(() => URL.revokeObjectURL(url), 10_000);
}
